"""
Unit tests for DOCX Generator Module
"""

import docx
from src.docx_generator import build_docx_resume


SAMPLE_RESUME = {
    "personal_info": {
        "full_name": "Elena Rostova",
        "professional_title": "Senior AI Researcher",
        "email": "elena@example.com",
        "phone": "+1 (555) 123-4567",
        "location": "Boston, MA",
        "linkedin": "https://linkedin.com/in/elenarostova",
    },
    "professional_summary": "Pioneering AI researcher with 5+ years specializing in transformer architectures.",
    "skills": {
        "programming_languages": ["Python", "C++"],
        "frameworks": ["PyTorch", "HuggingFace"],
    },
    "experience": [
        {
            "company": "DeepAI Labs",
            "role": "Lead Research Engineer",
            "duration": "2021 - Present",
            "location": "Boston, MA",
            "bullet_points": [
                "Spearheaded multi-modal model optimization reducing training costs by 30%.",
                "Mentored 6 junior researchers and published peer-reviewed findings.",
            ],
        }
    ],
    "projects": [
        {
            "name": "NeuroVision",
            "technologies": "PyTorch, CUDA",
            "urls": "https://github.com/elena/neurovision",
            "bullet_points": ["Created real-time edge segmentation pipeline."],
        }
    ],
    "education": [
        {
            "institution": "MIT",
            "degree": "M.S.",
            "field_of_study": "Computer Science",
            "year": "2019 - 2021",
            "gpa": "4.0",
            "highlights": "Published thesis on neural sparsity.",
        }
    ],
    "certifications": [
        {
            "name": "Deep Learning Specialization",
            "organization": "Coursera",
            "date": "2020",
        }
    ],
    "achievements": [
        "Best Paper Award at NeurIPS Workshop 2022",
    ],
}


def test_build_docx_resume():
    buffer = build_docx_resume(SAMPLE_RESUME)
    assert buffer is not None
    assert buffer.getbuffer().nbytes > 0

    # Verify that the generated bytes can be reopened cleanly by python-docx
    doc = docx.Document(buffer)
    all_text = "\n".join([p.text for p in doc.paragraphs])

    assert "ELENA ROSTOVA" in all_text
    assert "Senior AI Researcher" in all_text
    assert "PROFESSIONAL SUMMARY" in all_text
    assert "TECHNICAL SKILLS" in all_text
    assert "DeepAI Labs" in all_text
    assert "NeuroVision" in all_text
    assert "MIT" in all_text
    assert "Best Paper Award at NeurIPS Workshop 2022" in all_text
