"""
Pydantic schemas for the AI Resume Builder.
Defines strict, validated data structures for personal info, education, skills,
experience, projects, certifications, achievements, and the full resume document.
"""
from typing import List, Optional, Dict
from pydantic import BaseModel, Field, field_validator


class PersonalInfo(BaseModel):
    """Candidate's personal contact information."""
    full_name: str = Field(default="", description="Full legal or professional name")
    email: str = Field(default="", description="Professional email address")
    phone: str = Field(default="", description="Contact phone number with area/country code")
    location: str = Field(default="", description="City, State / Country")
    linkedin_url: str = Field(default="", description="LinkedIn profile URL")
    github_url: str = Field(default="", description="GitHub profile URL")
    portfolio_url: str = Field(default="", description="Personal website or portfolio URL")

    def is_empty(self) -> bool:
        return not any([
            self.full_name.strip(),
            self.email.strip(),
            self.phone.strip(),
            self.location.strip(),
        ])


class EducationEntry(BaseModel):
    """Single education institution entry."""
    institution: str = Field(default="", description="College, University, or School name")
    degree: str = Field(default="", description="Degree level, e.g. B.Tech, B.S., M.S., High School")
    field_of_study: str = Field(default="", description="Major or specialization, e.g. Computer Science")
    start_year: str = Field(default="", description="Year or Date started, e.g. 2022")
    end_year: str = Field(default="", description="Graduation year or Expected, e.g. 2026")
    gpa: str = Field(default="", description="CGPA or Percentage, e.g. 3.8/4.0 or 8.9/10")
    relevant_coursework: str = Field(
        default="", description="Comma-separated coursework e.g. Data Structures, Algorithms, DBMS"
    )

    def is_empty(self) -> bool:
        return not (self.institution.strip() or self.degree.strip())


class SkillCategory(BaseModel):
    """Custom categorized skills."""
    category_name: str = Field(default="", description="Category title e.g. Cloud & DevOps")
    skills: List[str] = Field(default_factory=list, description="List of skills under category")


class SkillsData(BaseModel):
    """Comprehensive categorized technical and soft skills."""
    programming_languages: List[str] = Field(
        default_factory=list, description="Languages e.g. Python, Java, C++, TypeScript"
    )
    frameworks: List[str] = Field(
        default_factory=list, description="Frameworks e.g. Streamlit, Flask, React, FastAPI"
    )
    tools: List[str] = Field(
        default_factory=list, description="Tools & Utilities e.g. Git, Docker, VS Code, Postman"
    )
    ai_ml: List[str] = Field(
        default_factory=list, description="AI/ML e.g. PyTorch, LangChain, RAG, Ollama, Scikit-learn"
    )
    databases: List[str] = Field(
        default_factory=list, description="Databases e.g. PostgreSQL, MongoDB, Redis, MySQL"
    )
    custom_categories: List[SkillCategory] = Field(
        default_factory=list, description="Additional user-defined skill categories"
    )

    def is_empty(self) -> bool:
        has_builtins = any([
            self.programming_languages,
            self.frameworks,
            self.tools,
            self.ai_ml,
            self.databases,
        ])
        has_custom = any(cat.skills for cat in self.custom_categories if cat.category_name.strip())
        return not (has_builtins or has_custom)


class ExperienceEntry(BaseModel):
    """Work experience or internship record."""
    company: str = Field(default="", description="Company or Organization name")
    role: str = Field(default="", description="Job Title, e.g. Software Engineering Intern")
    location: str = Field(default="", description="City, State / Remote")
    start_date: str = Field(default="", description="e.g. Jun 2024")
    end_date: str = Field(default="", description="e.g. Aug 2024 or Present")
    is_current: bool = Field(default=False, description="Is candidate currently working here?")
    responsibilities: str = Field(
        default="", description="Detailed responsibilities or bullet points"
    )
    achievements: str = Field(
        default="", description="Key measurable results or accomplishments"
    )
    improved_bullets: List[str] = Field(
        default_factory=list, description="ATS-optimized bullet points generated by AI"
    )

    def is_empty(self) -> bool:
        return not (self.company.strip() or self.role.strip())


class ProjectEntry(BaseModel):
    """Academic, personal, or open-source project."""
    name: str = Field(default="", description="Project Name")
    description: str = Field(default="", description="Brief problem and solution overview")
    technologies: List[str] = Field(
        default_factory=list, description="Tech stack items used in this project"
    )
    github_url: str = Field(default="", description="Source code repository URL")
    demo_url: str = Field(default="", description="Live deployment or video demo URL")
    key_contributions: str = Field(
        default="", description="Candidate's direct contributions and implementation details"
    )
    improved_bullets: List[str] = Field(
        default_factory=list, description="ATS-optimized bullet points generated by AI"
    )

    def is_empty(self) -> bool:
        return not self.name.strip()


class CertificationEntry(BaseModel):
    """Professional certification or license."""
    name: str = Field(default="", description="Name of Certification, e.g. AWS Certified Cloud Practitioner")
    issuer: str = Field(default="", description="Issuing body, e.g. Amazon Web Services")
    issue_date: str = Field(default="", description="Date issued, e.g. Jan 2024")
    credential_url: str = Field(default="", description="URL to verify certificate")

    def is_empty(self) -> bool:
        return not self.name.strip()


class AchievementEntry(BaseModel):
    """Awards, competitions, hackathons, and honors."""
    title: str = Field(default="", description="Award / Achievement title")
    issuer_or_event: str = Field(default="", description="Organizer or Event, e.g. Smart India Hackathon")
    date: str = Field(default="", description="Date achieved, e.g. Oct 2024")
    description: str = Field(default="", description="Brief description of the accomplishment")

    def is_empty(self) -> bool:
        return not self.title.strip()


class VolunteerEntry(BaseModel):
    """Volunteer or community leadership role."""
    organization: str = Field(default="", description="Organization or Community name")
    role: str = Field(default="", description="Volunteer position")
    dates: str = Field(default="", description="Time period, e.g. 2023 - 2024")
    details: str = Field(default="", description="Key activities and impact")

    def is_empty(self) -> bool:
        return not (self.organization.strip() or self.role.strip())


class TargetJob(BaseModel):
    """Target position and job description for ATS tailoring."""
    title: str = Field(default="", description="Desired job title e.g. Junior Backend Developer")
    job_description: str = Field(default="", description="Pasted job posting description")


class ResumeData(BaseModel):
    """Complete root Resume data structure containing all sections."""
    personal_info: PersonalInfo = Field(default_factory=PersonalInfo)
    summary: str = Field(default="", description="Professional summary paragraph")
    education: List[EducationEntry] = Field(default_factory=list)
    skills: SkillsData = Field(default_factory=SkillsData)
    experience: List[ExperienceEntry] = Field(default_factory=list)
    projects: List[ProjectEntry] = Field(default_factory=list)
    certifications: List[CertificationEntry] = Field(default_factory=list)
    achievements: List[AchievementEntry] = Field(default_factory=list)
    volunteer: List[VolunteerEntry] = Field(default_factory=list)
    target_job: TargetJob = Field(default_factory=TargetJob)

    # Template selection & section visibility preferences
    selected_template: str = Field(default="Classic ATS")
    enabled_sections: List[str] = Field(
        default_factory=lambda: [
            "Professional Summary",
            "Education",
            "Skills",
            "Experience",
            "Projects",
            "Certifications",
            "Achievements",
        ]
    )
